#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo chmod +r -R ./mediafiles/
chmod +r -R ./mediafiles/

python3 manage.py makemigrations --no-input
python3 manage.py migrate --no-input
python3 manage.py collectstatic --no-input
python3 manage.py runserver 0.0.0.0:8000
