# Generated by Django 3.2.11 on 2022-04-16 12:40

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+79999999999', max_length=30, region=None, verbose_name='phone number')),
                ('about_me', models.TextField(default='say something about yourself', verbose_name='about me')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=20, verbose_name='gender')),
                ('country', django_countries.fields.CountryField(default='RU', max_length=2, verbose_name='country')),
                ('city', models.CharField(default='Moscow', max_length=180, verbose_name='city')),
                ('profile_photo', models.ImageField(default='profile_default.png', upload_to='', verbose_name='profile photo')),
                ('twitter_handle', models.CharField(blank=True, max_length=20, verbose_name='twitter_handle')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='profiles.Profile')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
